### ISSUE TITLE
Wrong Log Date and Time shown: Mar 25 2015 15:00:00 UTC

### ISSUE THREAD

**Issue by Kirdnevs** [ArduPilot/UAVLogViewer#399] opened 2023-07-31 14:19 UTC
I'm using the online version of the tool at https://plot.ardupilot.org/ for visualisation and quick analysis of my logs.

Since few weeks the date and time of all of my logs is shown as Mar 25 2015 15:00:00 UTC

The error does not come from my logs. The timestamps are correct. Also files which worked correctly in the past are now also shown with the wrong time and date. 

The exact date when the tool stopped showing the correct time I cannot tell. I didnn't used the tool for 1-2 month (mid may to mid july)

The local version also isn't an alternative for me due to the issue #395

**Comment by AndKe** [comment] 2023-11-01 10:31
Log affected by this issue: https://drive.google.com/file/d/1LPinfPQbLsfKwo_GzhEuuNPsuV78kXQ3/view?usp=sharing

**Comment by Williangalvani** [comment] 2023-11-01 17:07
Hi, I just pushed an update to https://plotbeta.ardupilot.org, could you check it out?

**Comment by AndKe** [comment] 2023-11-01 17:32
@Williangalvani  - well done! - time works as expected - but it does not matter, because some catastrophe has apparentløy flooded the world:  :)
![image](https://github.com/ArduPilot/UAVLogViewer/assets/1468842/715b4971-957b-4f6c-93c6-67586db6c9d8)

**Comment by Williangalvani** [comment] 2023-11-02 01:28
> @Williangalvani - well done! - time works as expected - but it does not matter, because some catastrophe has apparently flooded the world: :) ![image](https://user-images.githubusercontent.com/1468842/279752804-715b4971-957b-4f6c-93c6-67586db6c9d8.png)

oh no, is everyone ok? 

have you tried turning it off and on again?
ctrl+shift+f5 could help too. it seems fine on my end :thinking:

**Comment by AndKe** [comment] 2023-11-02 08:36
> > oh no, is everyone ok 😅 ?

Yes, luckily our existence is apparently run by Firefox, where things worked, the issue was not reproducible in Vivaldi(Chromium) incognito window eighter, and CTRL-SHIFT-R (reload, do not use cache - fixed it )  :)   
Thank you.

**Comment by Williangalvani** [comment] 2023-11-02 12:01
cool, I'll close this issue, then =]

**Closed by Williangalvani** 2023-11-02 12:01 UTC

**Comment by be-ska** [comment] 2024-05-24 07:13
Hello @Williangalvani, I'm actually having the same issue:

<img width="1004" alt="Screenshot 2024-05-24 at 09 07 00" src="https://github.com/ArduPilot/UAVLogViewer/assets/72148330/932a538a-b94f-468b-aff7-31f6ec8429eb">

If the same log is opened with MAVexplorer.py, the right date is returned:
```
MAV> messages
MAV> 2024-04-05 14:01:17.750 ArduCopter V4.4.3 (b44b804b)
2024-04-05 14:01:17.750 ChibiOS: 17a50e3a
2024-04-05 14:01:17.750 CubeOrange 00300017 34305106 35383431
2024-04-05 14:01:17.750 Param space used: 1603/5376
2024-04-05 14:01:17.750 RC Protocol: SBUS
2024-04-05 14:01:17.750 RCOut: PWM:1-8 DS600:9-12
2024-04-05 14:01:17.750 New mission
2024-04-05 14:01:17.750 New rally
2024-04-05 14:01:17.750 New fence
```

**Comment by timvand** [comment] 2025-02-09 00:45
Nope, still an issue on the main site, and plotbeta displays the correct date, Feb 8 2025, and main site displays the date as Mar 25, 2015.

plot.ardupilot.org;

![Image](https://github.com/user-attachments/assets/bc071ca0-5883-4f9d-9ae8-b9b205dac49a)

plotbeta.ardupilot.org;

![Image](https://github.com/user-attachments/assets/689311f3-eeba-4d26-b002-75519097a298)
